import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./quill.css";
import "react-quill/dist/quill.snow.css";
import { SidebarDemo } from "@/components/Sidebar";
import { AuthProvider } from "@/provider/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
